// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQNL6xoBTxEJG9qmtqeD6YacYqhyJSuX8',
    appId: '1:464667760502:web:d9b75c284dc99ff3bb8c57',
    messagingSenderId: '464667760502',
    projectId: 'fir-app-d25d6',
    authDomain: 'fir-app-d25d6.firebaseapp.com',
    databaseURL: 'https://fir-app-d25d6-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-d25d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCInMdzPNB8Fqq105E2PYVdTLMjsDkK93U',
    appId: '1:464667760502:android:d740ec39e71adaf1bb8c57',
    messagingSenderId: '464667760502',
    projectId: 'fir-app-d25d6',
    databaseURL: 'https://fir-app-d25d6-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-d25d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlYOHNuCB3MLahVoEzkMpJN4eWDl6MPc',
    appId: '1:464667760502:ios:9ee58560e29d5218bb8c57',
    messagingSenderId: '464667760502',
    projectId: 'fir-app-d25d6',
    databaseURL: 'https://fir-app-d25d6-default-rtdb.firebaseio.com',
    storageBucket: 'fir-app-d25d6.appspot.com',
    iosClientId: '464667760502-t6oje2mbvgkb5p9achap1i6rus18t1s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.transportApp',
  );
}
